# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarQubePrepare@5
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'lucas-paulger-sonarsource'
    scannerMode: 'MSBuild'
    projectKey: 'lucas-paulger-sonarsource_dotnet-demo'
    projectName: 'dotnet-demo'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'sonar-dummy-dotnet-project.sln'

- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
