# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none # Disable CI triggers.

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'lucas-paulger-sonarsource'
    scannerMode: 'MSBuild'
    msBuildVersion: '9.0.0.100868'
    projectKey: 'lucas-paulger-sonarsource_dotnet-demo'
    projectName: 'dotnet-demo'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'sonar-dummy-dotnet-project.sln'

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'