# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none # Disable CI triggers.
pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Unsetting JAVA_HOME_17_X64
    set JAVA_HOME_17_X64=
    echo JAVA_HOME_17_X64 is now: %JAVA_HOME_17_X64%
  displayName: 'Emulate non-set JAVA_HOME_17_X64'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'MSBuild'
    msBuildVersion: '8.0.3.99785'
    projectKey: 'dotnet-demo'
    extraProperties: |
      sonar.scanner.skipJreProvisioning=true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'sonar-dummy-dotnet-project.sln'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'
